first_name=input("Please enter your first name:")
middle_name=input("Please enter your middle name:")
last_name=input("Please enter your last name:")
full_name=(first_name[0], middle_name[0], last_name[:])
intials=input("Your full name is:")
print(full_name)
